name: microcks-test-actions
on: [push]
jobs:
  microcks-test:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/microcks-test-action
        with:
          apiNameAndVersion: 'API Pastry - 2.0 - 2.0.0'
          testEndpoint: 'http://quarkus-api-pastry-api-pastry.apps.cluster-e7cb.e7cb.example.opentlc.com'
          runner: OPEN_API_SCHEMA
          microcksURL: 'https://microcks-microcks.apps.cluster-e7cb.e7cb.example.opentlc.com/api/'
          keycloakClientId: 'microcks-serviceaccount'
          keycloakClientSecret: 'ab54d329-e435-41ae-a900-ec6b3fe15c54'
          waitFor: '10sec'